# Generated by Django 4.2.16 on 2024-12-04 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0002_alter_obra_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(default='', upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
