# Generated by Django 4.2.16 on 2024-12-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0003_artista_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='foto',
        ),
    ]
