# Generated by Django 5.1.4 on 2024-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0004_remove_artista_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='foto',
            field=models.ImageField(default='', upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
