# Generated by Django 4.2.16 on 2024-12-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0007_remove_artista_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
