# Generated by Django 4.2.16 on 2024-12-11 00:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artistas', '0008_artista_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
