# Generated by Django 4.2.16 on 2024-12-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_eh_artista_remove_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='', upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
