<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-12-09 23:13
=======
# Generated by Django 5.1.4 on 2024-12-06 16:13
>>>>>>> 498d4e5156a9f6fbc25b2a663bf2642eb762e960

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_perfil_eh_artista_remove_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='', upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
