# Generated by Django 4.2.16 on 2024-12-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_biografia_perfil_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tipo_usuario',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='', upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
